### ISSUE TITLE
孫薪柏HW

### ISSUE THREAD

**Issue by nina9179** [dpes8693/frontend-mentor-program-1rd#14]
Lv1:https://codepen.io/Nina-the-solid/pen/bGJJKaM
Lv2:https://nina9179.github.io/孫薪柏HW.html

**Comment by dpes8693** [comment]
- Lv1 連結可開啟 ✅
- Lv2 連結可開啟 ✅
- 提出問題✅
  - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
  - 每周問題不重複
