### ISSUE TITLE
孫薪柏_issues

### ISSUE THREAD

**Issue by nina9179** [dpes8693/frontend-mentor-program-1rd#15]
我想請教，在寫CSS是否有甚麼技巧能讓排版更加豐富好看?

**Comment by dpes8693** [comment]
先分兩個問題點
1. 好看 & 豐富
每個人審美觀不同，我認為是視覺要設計出符合該網站產品的風格
再依照設計圖使用CSS實作出來
可以參考 `codepen` & `pinterest` 其他大神的設計風格

2. CSS排版
可以研究的關鍵字: `flex布局` `grid布局`
