### ISSUE TITLE
侯家蓁ＨＷ

### ISSUE THREAD

**Issue by Jennahou** [dpes8693/frontend-mentor-program-1rd#16]
LV1:https://codepen.io/Jennahou/pen/BaEemyV
LV2:https://jennahou.github.io/-.github.io/hw

**Comment by dpes8693** [comment]
- Lv1 連結可開啟 ✅
- Lv2 連結可開啟 ✅
- 提出問題✅
  - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
  - 每周問題不重複
