### ISSUE TITLE
陳冠銘 hm2&Q

### ISSUE THREAD

**Issue by Kuan14** [dpes8693/frontend-mentor-program-1rd#20]
link:
https://codepen.io/Kuan-the-solid/details/bGybMXX

Q:
在我的待辦清單應用中，有哪些方面可以進一步改進或優化，以提升使用者體驗和介面設計？

**Comment by dpes8693** [comment]
codepen 的 css 和 js 區塊
 不用放上`<style> <script>`標籤

**Comment by dpes8693** [comment]
- 連結可開啟 ✅ (Lv2)
- 已提出問題 ✅
    - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
    - 問題不重複

**Comment by dpes8693** [comment]
> link: https://codepen.io/Kuan-the-solid/details/bGybMXX
> 
> Q: 在我的待辦清單應用中，有哪些方面可以進一步改進或優化，以提升使用者體驗和介面設計？

課程上回覆
