### ISSUE TITLE
詹珀柚HW2 & Question

### ISSUE THREAD

**Issue by JamesChan0107** [dpes8693/frontend-mentor-program-1rd#21]
Link：
https://jameschan0107.github.io/ToDoList

Question：
想知道現在所學的資料結構和演算法，在實際工作和coding中，哪些方法最常使用或常見？

**Comment by dpes8693** [comment]
- 連結可開啟 ✅ (Lv3)
- 已提出問題 ✅
    - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
    - 問題不重複
