### ISSUE TITLE
侯家蓁week1 hw & question

### ISSUE THREAD

**Issue by Jennahou** [dpes8693/frontend-mentor-program-1rd#24]
Lv0、Lv1、Lv2
https://codepen.io/Jennahou/pen/NWVqLaw

**Comment by Jennahou** [comment]
question:
有查詢過ＤＯＭ的意思，但還不是很理解。

**Comment by dpes8693** [comment]
- 連結可開啟 ✅ (Lv2)
- 已提出問題 ✅
    - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
    - 問題不重複

**Comment by dpes8693** [comment]
> question: 有查詢過ＤＯＭ的意思，但還不是很理解。

課堂上會再說明

參考資料:
<https://ithelp.ithome.com.tw/articles/10313326>
