### ISSUE TITLE
詹珀柚HW3 & Question

### ISSUE THREAD

**Issue by JamesChan0107** [dpes8693/frontend-mentor-program-1rd#30]
１.改良後的ToDoList：https://jameschan0107.github.io/todolist

２.ES6-Note：https://github.com/JamesChan0107/ES6-Note

３.問題：想請問製作RWD網頁，若是想要用比較華麗的特效，是不是不太適合？以及製作RWD上有甚麼其他比較顯著的缺點？

**Comment by dpes8693** [comment]
- 筆記repo ✅
- 連結可開啟 ✅ (Lv4)
- 已提出問題 ✅
    - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
    - 問題不重複

**Comment by dpes8693** [comment]
> １.改良後的ToDoList：https://jameschan0107.github.io/todolist
> 
> ２.ES6-Note：https://github.com/JamesChan0107/ES6-Note
> 
> ３.問題：想請問製作RWD網頁，若是想要用比較華麗的特效，是不是不太適合？以及製作RWD上有甚麼其他比較顯著的缺點？

要看華麗的特效在不同裝置是否會跑版，會跑就要額外調整
如果有做到大量粒子特效的網頁在效能低的手機上，會很影響體驗
所適不適合要看裝置

我認為RWD唯一的缺點就是開發的時間成本比較高

**Comment by dpes8693** [comment]
特效範例:
https://echarts.apache.org/examples/zh/editor.html?c=graphgl-large-internet&gl=1&theme=dark
