### ISSUE TITLE
侯家蓁week2 hw

### ISSUE THREAD

**Issue by Jennahou** [dpes8693/frontend-mentor-program-1rd#33]
lv4:
https://codepen.io/Jennahou/pen/zYQqZgM
es6:
https://github.com/Jennahou/es6_note.git
問題：
想再更了解箭頭函數。

**Comment by dpes8693** [comment]
- 筆記 ✅ => 但是 不是 markdown
- 連結可開啟 ✅ (Lv4)
- 已提出問題 ✅
    - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
    - 問題不重複

**Comment by dpes8693** [comment]
> lv4: https://codepen.io/Jennahou/pen/zYQqZgM es6: https://github.com/Jennahou/es6_note.git 問題： 想再更了解箭頭函數。

需要先不用複製的方式自己將語法打出來
再把其他疑問列出來
