### ISSUE TITLE
詹珀柚_想提問的問題

### ISSUE THREAD

**Issue by JamesChan0107** [dpes8693/frontend-mentor-program-1rd#5]
1.成為軟體工程師，碩士學歷以及校名是否重要？會問是因為很多人的看法很兩極
2.軟體工程師平常會不會使用ChatGPT等生成式AI來幫助Coding？

**Comment by dpes8693** [comment]
1. https://www.standup-for-rights.work/post/q00001/
2. https://www.standup-for-rights.work/post/q00002/
