### ISSUE TITLE
陳冠銘 HW6&Q

### ISSUE THREAD

**Issue by Kuan14** [dpes8693/frontend-mentor-program-1rd#54]
link : https://github.com/Kuan14/java-/blob/main/async.md
Q : 1.我筆記提到的範例funcA ()、funcB()、funcC()第一個用.then()的方法算同步嗎？ 如果在funcA()就reject還會執行funcB()嗎，還是會顯示什麼，另外，不是很清楚什麼情況會reject
2.非同步 funcA()如果reject ，funcB()、funcC()會繼續跑嗎？

**Comment by dpes8693** [comment]
- 連結可開啟 ✅
- 已提出問題 ✅
    - [每周]蒐集學生對於{未來成為軟體工程師}的 問題/疑惑/好奇
    - 問題不重複

**Comment by dpes8693** [comment]
> link : https://github.com/Kuan14/java-/blob/main/async.md Q : 1.我筆記提到的範例funcA ()、funcB()、funcC()第一個用.then()的方法算同步嗎？ 如果在funcA()就reject還會執行funcB()嗎，還是會顯示什麼，另外，不是很清楚什麼情況會reject 2.非同步 funcA()如果reject ，funcB()、funcC()會繼續跑嗎？
