### ISSUE TITLE
鄭鈞文_question

### ISSUE THREAD

**Issue by wdOq** [dpes8693/frontend-mentor-program-1rd#7]
1.請問走前後端的工程師有甚麼推薦的證照或是課程需要學習嗎?
2.軟體公司面試時我們需要準備github的作品嗎還是會有其他看重的項目?

**Comment by dpes8693** [comment]
1. https://www.standup-for-rights.work/post/q00005/
2. https://www.standup-for-rights.work/post/q00006/
